#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AddCertificateCredential")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class AddCertificateCredentialRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public System.Guid entityId
		{
			get
			{
				if (this.Parameters.Contains("entityId"))
				{
					return ((System.Guid)(this.Parameters["entityId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["entityId"] = value;
			}
		}
		
		public string entityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("entityLogicalName"))
				{
					return ((string)(this.Parameters["entityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entityLogicalName"] = value;
			}
		}
		
		public string thumbprint
		{
			get
			{
				if (this.Parameters.Contains("thumbprint"))
				{
					return ((string)(this.Parameters["thumbprint"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["thumbprint"] = value;
			}
		}
		
		public AddCertificateCredentialRequest()
		{
			this.RequestName = "AddCertificateCredential";
			this.entityId = default(System.Guid);
			this.entityLogicalName = default(string);
			this.thumbprint = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AddCertificateCredential")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class AddCertificateCredentialResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public AddCertificateCredentialResponse()
		{
		}
	}
}
#pragma warning restore CS1591
