#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/budget/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("budget_budget_logicSetWhatTypeDisplayName")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_budget_logicSetWhatTypeDisplayNameRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public budget_budget_logicSetWhatTypeDisplayNameRequest()
		{
			this.RequestName = "budget_budget_logicSetWhatTypeDisplayName";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/budget/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("budget_budget_logicSetWhatTypeDisplayName")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_budget_logicSetWhatTypeDisplayNameResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public budget_budget_logicSetWhatTypeDisplayNameResponse()
		{
		}
	}
}
#pragma warning restore CS1591
