#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("budget_InteropRowUpsert")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_InteropRowUpsertRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string entitylogicalname
		{
			get
			{
				if (this.Parameters.Contains("entitylogicalname"))
				{
					return ((string)(this.Parameters["entitylogicalname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entitylogicalname"] = value;
			}
		}
		
		public string JsonBody
		{
			get
			{
				if (this.Parameters.Contains("JsonBody"))
				{
					return ((string)(this.Parameters["JsonBody"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["JsonBody"] = value;
			}
		}
		
		public string origination
		{
			get
			{
				if (this.Parameters.Contains("origination"))
				{
					return ((string)(this.Parameters["origination"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["origination"] = value;
			}
		}
		
		public string action
		{
			get
			{
				if (this.Parameters.Contains("action"))
				{
					return ((string)(this.Parameters["action"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["action"] = value;
			}
		}
		
		public budget_InteropRowUpsertRequest()
		{
			this.RequestName = "budget_InteropRowUpsert";
			this.entitylogicalname = default(string);
			this.JsonBody = default(string);
			this.origination = default(string);
			this.action = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("budget_InteropRowUpsert")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_InteropRowUpsertResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public budget_InteropRowUpsertResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference EntityReference
		{
			get
			{
				if (this.Results.Contains("EntityReference"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["EntityReference"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
		}
		
		public string result
		{
			get
			{
				if (this.Results.Contains("result"))
				{
					return ((string)(this.Results["result"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string resultmessage
		{
			get
			{
				if (this.Results.Contains("result-message"))
				{
					return ((string)(this.Results["result-message"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
