#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("budget_CurrentFY")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_CurrentFYRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public budget_CurrentFYRequest()
		{
			this.RequestName = "budget_CurrentFY";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("budget_CurrentFY")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_CurrentFYResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public budget_CurrentFYResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity FiscalYear
		{
			get
			{
				if (this.Results.Contains("FiscalYear"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["FiscalYear"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
		}
	}
}
#pragma warning restore CS1591
