#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("budget_FYByDate")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_FYByDateRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public System.DateTime date
		{
			get
			{
				if (this.Parameters.Contains("date"))
				{
					return ((System.DateTime)(this.Parameters["date"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["date"] = value;
			}
		}
		
		public budget_FYByDateRequest()
		{
			this.RequestName = "budget_FYByDate";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("budget_FYByDate")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_FYByDateResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public budget_FYByDateResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity FiscalYear
		{
			get
			{
				if (this.Results.Contains("FiscalYear"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["FiscalYear"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
		}
	}
}
#pragma warning restore CS1591
