#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("budget_InteropOriginationProcessRetrieveActionBody")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_InteropOriginationProcessRetrieveActionBodyRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string ItemInternalId
		{
			get
			{
				if (this.Parameters.Contains("ItemInternalId"))
				{
					return ((string)(this.Parameters["ItemInternalId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ItemInternalId"] = value;
			}
		}
		
		public string entitylogicalname
		{
			get
			{
				if (this.Parameters.Contains("entitylogicalname"))
				{
					return ((string)(this.Parameters["entitylogicalname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entitylogicalname"] = value;
			}
		}
		
		public string base64actionbody
		{
			get
			{
				if (this.Parameters.Contains("base64actionbody"))
				{
					return ((string)(this.Parameters["base64actionbody"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["base64actionbody"] = value;
			}
		}
		
		public budget_InteropOriginationProcessRetrieveActionBodyRequest()
		{
			this.RequestName = "budget_InteropOriginationProcessRetrieveActionBody";
			this.ItemInternalId = default(string);
			this.entitylogicalname = default(string);
			this.base64actionbody = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("budget_InteropOriginationProcessRetrieveActionBody")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_InteropOriginationProcessRetrieveActionBodyResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public budget_InteropOriginationProcessRetrieveActionBodyResponse()
		{
		}
		
		public string base64actionbody
		{
			get
			{
				if (this.Results.Contains("base64actionbody"))
				{
					return ((string)(this.Results["base64actionbody"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
