#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("budget_organizationinfo")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_organizationinfoRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public budget_organizationinfoRequest()
		{
			this.RequestName = "budget_organizationinfo";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("budget_organizationinfo")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_organizationinfoResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public budget_organizationinfoResponse()
		{
		}
		
		public string environmentid
		{
			get
			{
				if (this.Results.Contains("environmentid"))
				{
					return ((string)(this.Results["environmentid"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string friendlyname
		{
			get
			{
				if (this.Results.Contains("friendlyname"))
				{
					return ((string)(this.Results["friendlyname"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string geo
		{
			get
			{
				if (this.Results.Contains("geo"))
				{
					return ((string)(this.Results["geo"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string organizationid
		{
			get
			{
				if (this.Results.Contains("organizationid"))
				{
					return ((string)(this.Results["organizationid"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string organizationtype
		{
			get
			{
				if (this.Results.Contains("organizationtype"))
				{
					return ((string)(this.Results["organizationtype"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string uniquename
		{
			get
			{
				if (this.Results.Contains("uniquename"))
				{
					return ((string)(this.Results["uniquename"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string webappurl
		{
			get
			{
				if (this.Results.Contains("webappurl"))
				{
					return ((string)(this.Results["webappurl"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
