#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("budget_AddInteropUpdateOriginator")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_AddInteropUpdateOriginatorRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string entitylogicalname
		{
			get
			{
				if (this.Parameters.Contains("entitylogicalname"))
				{
					return ((string)(this.Parameters["entitylogicalname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entitylogicalname"] = value;
			}
		}
		
		public budget_AddInteropUpdateOriginatorRequest()
		{
			this.RequestName = "budget_AddInteropUpdateOriginator";
			this.entitylogicalname = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("budget_AddInteropUpdateOriginator")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class budget_AddInteropUpdateOriginatorResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public budget_AddInteropUpdateOriginatorResponse()
		{
		}
		
		public string result
		{
			get
			{
				if (this.Results.Contains("result"))
				{
					return ((string)(this.Results["result"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string resultmessage
		{
			get
			{
				if (this.Results.Contains("result-message"))
				{
					return ((string)(this.Results["result-message"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
