#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_knowledgeHarvestCreateArticle")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_knowledgeHarvestCreateArticleRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public System.Guid msdyn_entityId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_entityId"))
				{
					return ((System.Guid)(this.Parameters["msdyn_entityId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["msdyn_entityId"] = value;
			}
		}
		
		public System.Guid msdyn_knowledgeHarvestJobId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_knowledgeHarvestJobId"))
				{
					return ((System.Guid)(this.Parameters["msdyn_knowledgeHarvestJobId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["msdyn_knowledgeHarvestJobId"] = value;
			}
		}
		
		public string msdyn_payload
		{
			get
			{
				if (this.Parameters.Contains("msdyn_payload"))
				{
					return ((string)(this.Parameters["msdyn_payload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_payload"] = value;
			}
		}
		
		public string msdyn_entityName
		{
			get
			{
				if (this.Parameters.Contains("msdyn_entityName"))
				{
					return ((string)(this.Parameters["msdyn_entityName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_entityName"] = value;
			}
		}
		
		public msdyn_knowledgeHarvestCreateArticleRequest()
		{
			this.RequestName = "msdyn_knowledgeHarvestCreateArticle";
			this.msdyn_entityId = default(System.Guid);
			this.msdyn_knowledgeHarvestJobId = default(System.Guid);
			this.msdyn_payload = default(string);
			this.msdyn_entityName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_knowledgeHarvestCreateArticle")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_knowledgeHarvestCreateArticleResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_knowledgeHarvestCreateArticleResponse()
		{
		}
		
		public string msdyn_apiResponse
		{
			get
			{
				if (this.Results.Contains("msdyn_apiResponse"))
				{
					return ((string)(this.Results["msdyn_apiResponse"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
