#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetIntentAssistSuggestionsForBot")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetIntentAssistSuggestionsForBotRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string IntentAssistForBotRequest
		{
			get
			{
				if (this.Parameters.Contains("IntentAssistForBotRequest"))
				{
					return ((string)(this.Parameters["IntentAssistForBotRequest"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IntentAssistForBotRequest"] = value;
			}
		}
		
		public msdyn_GetIntentAssistSuggestionsForBotRequest()
		{
			this.RequestName = "msdyn_GetIntentAssistSuggestionsForBot";
			this.IntentAssistForBotRequest = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetIntentAssistSuggestionsForBot")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetIntentAssistSuggestionsForBotResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetIntentAssistSuggestionsForBotResponse()
		{
		}
		
		public string IntentAssistForBotResponse
		{
			get
			{
				if (this.Results.Contains("IntentAssistForBotResponse"))
				{
					return ((string)(this.Results["IntentAssistForBotResponse"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
