#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetPostOperations")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetPostOperationsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public System.Guid correlationId
		{
			get
			{
				if (this.Parameters.Contains("correlationId"))
				{
					return ((System.Guid)(this.Parameters["correlationId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["correlationId"] = value;
			}
		}
		
		public System.Guid workflowId
		{
			get
			{
				if (this.Parameters.Contains("workflowId"))
				{
					return ((System.Guid)(this.Parameters["workflowId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["workflowId"] = value;
			}
		}
		
		public msdyn_GetPostOperationsRequest()
		{
			this.RequestName = "msdyn_GetPostOperations";
			this.correlationId = default(System.Guid);
			this.workflowId = default(System.Guid);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetPostOperations")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetPostOperationsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetPostOperationsResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection postOperations
		{
			get
			{
				if (this.Results.Contains("postOperations"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["postOperations"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
		}
	}
}
#pragma warning restore CS1591
