#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_OSGetAllOpportunityPredictionModels")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_OSGetAllOpportunityPredictionModelsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public msdyn_OSGetAllOpportunityPredictionModelsRequest()
		{
			this.RequestName = "msdyn_OSGetAllOpportunityPredictionModels";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_OSGetAllOpportunityPredictionModels")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_OSGetAllOpportunityPredictionModelsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_OSGetAllOpportunityPredictionModelsResponse()
		{
		}
		
		public string Predictions
		{
			get
			{
				if (this.Results.Contains("Predictions"))
				{
					return ((string)(this.Results["Predictions"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
