#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ojag/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ojag_GetNextAutoNumberByKey")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class ojag_GetNextAutoNumberByKeyRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string UniqueKey
		{
			get
			{
				if (this.Parameters.Contains("UniqueKey"))
				{
					return ((string)(this.Parameters["UniqueKey"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["UniqueKey"] = value;
			}
		}
		
		public int Seed
		{
			get
			{
				if (this.Parameters.Contains("Seed"))
				{
					return ((int)(this.Parameters["Seed"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["Seed"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public ojag_GetNextAutoNumberByKeyRequest()
		{
			this.RequestName = "ojag_GetNextAutoNumberByKey";
			this.UniqueKey = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/ojag/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ojag_GetNextAutoNumberByKey")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class ojag_GetNextAutoNumberByKeyResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ojag_GetNextAutoNumberByKeyResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Registry
		{
			get
			{
				if (this.Results.Contains("Registry"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["Registry"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
		}
		
		public int Value
		{
			get
			{
				if (this.Results.Contains("Value"))
				{
					return ((int)(this.Results["Value"]));
				}
				else
				{
					return default(int);
				}
			}
		}
	}
}
#pragma warning restore CS1591
