#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ojag_hasprivilege")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class ojag_hasprivilegeRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string privilegeName
		{
			get
			{
				if (this.Parameters.Contains("privilegeName"))
				{
					return ((string)(this.Parameters["privilegeName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["privilegeName"] = value;
			}
		}
		
		public ojag_hasprivilegeRequest()
		{
			this.RequestName = "ojag_hasprivilege";
			this.privilegeName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ojag_hasprivilege")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class ojag_hasprivilegeResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ojag_hasprivilegeResponse()
		{
		}
		
		public bool hasPrivelage
		{
			get
			{
				if (this.Results.Contains("hasPrivelage"))
				{
					return ((bool)(this.Results["hasPrivelage"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
}
#pragma warning restore CS1591
