#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ojag_appmoduleinfo")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class ojag_appmoduleinfoRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string uniquename
		{
			get
			{
				if (this.Parameters.Contains("uniquename"))
				{
					return ((string)(this.Parameters["uniquename"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["uniquename"] = value;
			}
		}
		
		public ojag_appmoduleinfoRequest()
		{
			this.RequestName = "ojag_appmoduleinfo";
			this.uniquename = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ojag_appmoduleinfo")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class ojag_appmoduleinfoResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ojag_appmoduleinfoResponse()
		{
		}
		
		public string appmoduleid
		{
			get
			{
				if (this.Results.Contains("appmoduleid"))
				{
					return ((string)(this.Results["appmoduleid"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string name
		{
			get
			{
				if (this.Results.Contains("name"))
				{
					return ((string)(this.Results["name"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string webresourceid
		{
			get
			{
				if (this.Results.Contains("webresourceid"))
				{
					return ((string)(this.Results["webresourceid"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
