#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStrata.Xrm.Sdk
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ojag_ExecuteEnvironmentDevopsActionV2")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class ojag_ExecuteEnvironmentDevopsActionV2Request : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string comment
		{
			get
			{
				if (this.Parameters.Contains("comment"))
				{
					return ((string)(this.Parameters["comment"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["comment"] = value;
			}
		}
		
		public string action
		{
			get
			{
				if (this.Parameters.Contains("action"))
				{
					return ((string)(this.Parameters["action"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["action"] = value;
			}
		}
		
		public ojag_ExecuteEnvironmentDevopsActionV2Request()
		{
			this.RequestName = "ojag_ExecuteEnvironmentDevopsActionV2";
			this.comment = default(string);
			this.action = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ojag_ExecuteEnvironmentDevopsActionV2")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class ojag_ExecuteEnvironmentDevopsActionV2Response : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ojag_ExecuteEnvironmentDevopsActionV2Response()
		{
		}
		
		public string action
		{
			get
			{
				if (this.Results.Contains("action"))
				{
					return ((string)(this.Results["action"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string actionId
		{
			get
			{
				if (this.Results.Contains("actionId"))
				{
					return ((string)(this.Results["actionId"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string name
		{
			get
			{
				if (this.Results.Contains("name"))
				{
					return ((string)(this.Results["name"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string payload
		{
			get
			{
				if (this.Results.Contains("payload"))
				{
					return ((string)(this.Results["payload"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string webhookrequestdetails
		{
			get
			{
				if (this.Results.Contains("webhookrequestdetails"))
				{
					return ((string)(this.Results["webhookrequestdetails"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string webhookresultcontent
		{
			get
			{
				if (this.Results.Contains("webhookresultcontent"))
				{
					return ((string)(this.Results["webhookresultcontent"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string webhookstatuscode
		{
			get
			{
				if (this.Results.Contains("webhookstatuscode"))
				{
					return ((string)(this.Results["webhookstatuscode"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
