#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace OpenStrata.Xrm.Sdk
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class OrgSvc : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public OrgSvc(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="OpenStrata.Xrm.Sdk.Organization"/> entities.
		/// </summary>
		public System.Linq.IQueryable<OpenStrata.Xrm.Sdk.Organization> OrganizationSet
		{
			get
			{
				return this.CreateQuery<OpenStrata.Xrm.Sdk.Organization>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="OpenStrata.Xrm.Sdk.Publisher"/> entities.
		/// </summary>
		public System.Linq.IQueryable<OpenStrata.Xrm.Sdk.Publisher> PublisherSet
		{
			get
			{
				return this.CreateQuery<OpenStrata.Xrm.Sdk.Publisher>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="OpenStrata.Xrm.Sdk.Solution"/> entities.
		/// </summary>
		public System.Linq.IQueryable<OpenStrata.Xrm.Sdk.Solution> SolutionSet
		{
			get
			{
				return this.CreateQuery<OpenStrata.Xrm.Sdk.Solution>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="OpenStrata.Xrm.Sdk.SolutionComponent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<OpenStrata.Xrm.Sdk.SolutionComponent> SolutionComponentSet
		{
			get
			{
				return this.CreateQuery<OpenStrata.Xrm.Sdk.SolutionComponent>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="OpenStrata.Xrm.Sdk.Workflow"/> entities.
		/// </summary>
		public System.Linq.IQueryable<OpenStrata.Xrm.Sdk.Workflow> WorkflowSet
		{
			get
			{
				return this.CreateQuery<OpenStrata.Xrm.Sdk.Workflow>();
			}
		}
	}
}
#pragma warning restore CS1591
